version: '3.4'

networks:
  my-dapr-netowork:
    # external: false

services:
  ############################
  # web applications
  ############################
  daprwebapp:
    build:
      context: ./DaprWebApp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "51000:50001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - daprrestapi
    networks:
      - my-dapr-netowork

  daprwebapp-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "daprwebapp",
      "-app-port", "3000",
      "-placement-host-address", "placement:50006",
      "-dapr-grpc-port", "50001",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - daprwebapp
    network_mode: "service:daprwebapp"

  ############################
  # rest apis
  ############################
  daprrestapi:
    build:
      context: ./DaprRestApi
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "50001:50001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # depends_on:
    #   - zipkin
    networks:
      - my-dapr-netowork

  daprrestapi-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "daprrestapi",
      "-app-port", "3001",
      "-placement-host-address", "placement:50006",
      "-dapr-grpc-port", "50001",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - daprrestapi
    network_mode: "service:daprrestapi"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - my-dapr-netowork
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - my-dapr-netowork
  ############################
  # Metrics Zipkin
  ############################
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - my-dapr-netowork

  zipkin-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "zipkin",
      "-app-port", "9411",
      "-placement-host-address", "placement:50006",
      "-dapr-grpc-port", "50001",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - zipkin
    network_mode: "service:zipkin"

  ############################
  # cosmos-db local emulator
  # acess to exploler https://localhost:8081/_explorer/index.html
  ############################
  # cosmos-db-emulator:
  #   image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
  #   tty: true
  #   ports:
  #     - 8081:8081
  #     - 10251:10251
  #     - 10252:10252
  #     - 10253:10253
  #     - 10254:10254
  #     - 10255:10255
  #   environment:
  #     - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
  #     - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
  #   deploy: # Use these param at v3 & add `–compatibility` when compose up
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: 3g