version: '3.4'

services:
  daprwebapp:
    build:
      context: ./DaprWebApp
      dockerfile: DaprWebApp/Dockerfile

  daprrestapi:
    build:
      context: ./DaprRestApi
      dockerfile: DaprRestApi/Dockerfile
