apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: checkout
spec:
  type: bindings.kafka
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: broker:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: sample_topic
  - name: consumerGroup
    value: sample_consumer 
  publisher configuration: topic
  - name: publishTopic
    value: sample_topic
  - name: authRequired
    value: "false"
